version: 2
name: base
displayName: Base Agent Catalog
registry:
  github-official:
    description: "Schema version control"
    title: "GitHub"
    type: "server"
    image: "mcp/github-official"
    env:
      - name: GITHUB_PERSONAL_ACCESS_TOKEN
        value: ""
